#!/bin/bash -e

. config.conf

BASEDIR=$(pwd)



if [ "$DOWNLOAD_PJSIP" == "1" ]
then
    cd "${BASEDIR}"
    rm -fr "${PJSIP_DIR_NAME}"
    echo "PJSIP downloaded!"
    echo "Extracting PJSIP ..."
    tar xjf pjproject-2.4.5.tar.bz2

    if [ "${PJSIP_DIR_NAME}" == "pjproject-2.4.5" ]
    then
        echo "Fix BASH script error in 2.4.5 tag ..."
        sed -i 's/TARGET_HOST+=-linux-android/TARGET_HOST="\${TARGET_HOST}-linux-android"/g' "${BASEDIR}/${PJSIP_DIR_NAME}/configure-android"

        echo "Apply patch to support G.729 codec without Intel IPP codec library ..."
        cd g729_patch
        ./install.sh
        cd ..
    fi
fi

if [ "$DOWNLOAD_SWIG" == "1" ]
then
    echo "Downloading SWIG ..."
    cd "${BASEDIR}"
    rm -fr "$SWIG_DIR_NAME"
    echo "SWIG downloaded!"
    echo "Extracting SWIG ..."
    tar xzf swig.tar.gz
    cd "$SWIG_DIR_NAME"
    ./configure
    make && sudo make install
    cd ..
    rm -rf "$SWIG_DIR_NAME"
fi

if [ "$DOWNLOAD_OPENSSL" == "1" ]
then
    echo "Downloading OpenSSL ..."
    cd "${BASEDIR}"
    curl -L -# -o openssl.tar.gz "$OPENSSL_DOWNLOAD_URL" 2>&1
    rm -rf "$OPENSSL_DIR_NAME"
    echo "OpenSSL downloaded!"
    echo "Extracting OpenSSL ..."
    tar xzf openssl.tar.gz && rm -rf openssl.tar.gz
    cd ${BASEDIR}
    ./openssl-build-target-archs
fi

if [ "$DOWNLOAD_LIBYUV" == "1" ]
then
    echo "Downloading libyuv ..."
    cd "${BASEDIR}"
    cd "${LIBYUV_REPO_DIR_NAME}"
    export PATH="${BASEDIR}/${NDK_DIR_NAME}:$PATH"
    sed -i 's/APP_ABI := armeabi armeabi-v7a arm64-v8a x86/APP_ABI := armeabi armeabi-v7a arm64-v8a x86 x86_64 mips mips64/g' jni/Application.mk
    ndk-build
fi

if [ "$DOWNLOAD_OPENH264" == "1" ]
then
    echo "Downloading OpenH264 ..."
    cd "${BASEDIR}"
    rm -rf "${OPENH264_DIR_NAME}"
    echo "OpenH264 downloaded!"
    echo "Extracting OpenH264 ..."
    tar xzf openh264.tar.gz
    if [ "${OPENH264_DIR_NAME}" == "openh264-1.0.0" ]
    then
        echo "Patching OpenH264 to be able to compile with Android API 21+.."
        cp ${BASEDIR}/openh264-1.0.0-android21.patch ${BASEDIR}/${OPENH264_DIR_NAME}/
        cd ${OPENH264_DIR_NAME} && patch -p1 < openh264-1.0.0-android21.patch || true
    fi
    cd ${BASEDIR}
    ./openh264-build-target-archs || true
fi

echo "The build system is ready! Execute: ./build to build PJSIP :)"

