#!/bin/bash -e

. config.conf
BASE_DIR=$(pwd)

export ANDROID_NDK_ROOT="${BASE_DIR}/${NDK_DIR_NAME}"
export NDK_SYSROOT="${ANDROID_NDK_ROOT}/platforms/android-${TARGET_ANDROID_API}/arch-arm"
export PREBUILT=$ANDROID_NDK_ROOT/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86
export PATH="$ANDROID_NDK_ROOT:$PATH"
rm -fr ${BASE_DIR}/x264-output
rm -fr ${BASE_DIR}/opus-output
rm -fr ${BASE_DIR}/vpx-output
rm -fr ${BASE_DIR}/ffmpeg-output
rm -fr ${BASE_DIR}/${X264_DIR_NAME}
rm -fr ${BASE_DIR}/${OPUS_DIR_NAME}
rm -fr ${BASE_DIR}/${LIBVPX_DIR_NAME}

if [ "$HAS_SWIG" == "1" ]
then
    echo "Configuring SWIG ..."
    cd "${BASE_DIR}"
    rm -fr "$SWIG_DIR_NAME"
    echo "Extracting SWIG ..."
    tar xzf swig.tar.gz
    cd "$SWIG_DIR_NAME"
    ./configure
    make && sudo make install
    cd ..
    rm -rf "$SWIG_DIR_NAME"
fi


if [ "$HAS_X264" == "1" ]
then
    echo "Configuring X264"
    cd "${BASE_DIR}"
    
    tar xjf x264.tar.bz2
    cd "${X264_DIR_NAME}"
    
   ./configure --cross-prefix=$PREBUILT/bin/arm-linux-androideabi- --sysroot=$NDK_SYSROOT --host=arm-linux --enable-pic --enable-static --disable-cli --prefix=${BASE_DIR}/x264-output

fi

if [ "$HAS_OPUS" == "1" ]
then
   echo "Configuring OPUS"
   cd "${BASE_DIR}"

   tar -zxf opus-1.1.1.tar.gz
   cd "${OPUS_DIR_NAME}"

   $ANDROID_NDK_ROOT/build/tools/make-standalone-toolchain.sh --platform=android-"${TARGET_ANDROID_API}" --arch=arm --install-dir=/tmp/my_toolchain
    export PATH=/tmp/my_toolchain/bin/:$PATH
    export CC=arm-linux-androideabi-gcc
    export CXX=arm-linux-androideabi-g++

   ./configure --prefix=${BASE_DIR}/opus-output --host=arm-linux-androideabi 
    
fi

if [ "$HAS_LIBVPX" == "1" ]
then
    echo "Configuring VPX"
    cd "${BASE_DIR}"
    
    unzip libvpx-master.zip
    cd "${LIBVPX_DIR_NAME}"
   ./configure --target=armv7-android-gcc --disable-examples --disable-docs --enable-pic --enable-vp8 --disable-vp9 --disable-vp10 --disable-runtime-cpu-detect --extra-cflags="-mfloat-abi=softfp -mfpu=neon" --disable-webm-io --sdk-path=$ANDROID_NDK_ROOT --target=armv7-android-gcc  --prefix=${BASE_DIR}/vpx-output
   
fi


echo "The build system is ready! Execute: ./build to build PJSIP :)"

